### PR TITLE
Remove Python 2 support

### PR DESCRIPTION
**Pull request by jrs65**

### CODE REVIEW

**Comment by jrs65** [comment]
I've ported this one, but not the other chimedb modules as this one used `future` in the `setup.py` without specifying it as build requirement in a `pyproject.toml` and hence it was breaking as it wasn't causing `future` to get installed beforehand.

**Comment by jrs65** [comment]
I've ported this one, but not the other chimedb modules as this one used `future` in the `setup.py` without specifying it as build requirement in a `pyproject.toml` and hence it was breaking as it wasn't causing `future` to get installed beforehand.

**Comment by jrs65** [comment]
This is such a rabbit hole. 😠

**Comment by jrs65** [comment]
Grrrr... okay. This new one is to do with the new pip resolver. While installing ch_util it's attempting to install ch_util, but it can't get it because of permissions on the repository. @anjakefala did you ever figure out a better way to do this other than going back to the old resolver.

**Comment by anjakefala** [comment]
@jrs65, no, I am pretty sure it's a bug in the resolver. I noticed similar issues in the pip repository Issues (will review and make sure), and I am hoping it will get fixed before they remove the legacy resolver.

An alternative is to hard code the pip version on the system to 20.2.

**Comment by anjakefala** [comment]
https://github.com/pypa/pip/issues/9229
https://github.com/pypa/pip/issues/9217

**Comment by anjakefala** [comment]
We may need to update the requirements.txt for all of our packages to ensure consistency in url formatting.

**Comment by anjakefala** [comment]
Oh sorry

> While installing ch_util it's attempting to install ch_util, but it can't get it because of permissions on the repository. 

This is not to do with the resolver. This is to do with the fact that chimedb_dataflag does not have secrets key access to private chime-experiment repositories. You will need to pre-install with ch_util-stub.

https://github.com/chime-experiment/ch_stubs

Example: https://github.com/chime-experiment/theremin/blob/ec1e23e2c2fc42a6eca5a2170ffe4969fccc73fc/.github/workflows/main.yml#L63

**Comment by ketiltrout** [comment]
Is the only reason you're pulling in `ch_util` for `csd_to_unix`?  Just make a dummy function for the tests.

**Comment by jrs65** [comment]
These reason it's to do with the resolver is that the workflow already checks out a copy of the full ch_util repo (via a secret key) and it fails when installing that, because a dependency lists `ch_util @ git+....` as it's own dependency. This worked before the new pip resolver as the old one seems to realise that the one being installed should satisfy the dependency.

**Comment by jrs65** [comment]
I'm trying to understand the underlying problem with the new resolver. I *think* it's that it treats the `ch_util @ <spec>` part as not just where to find the dependency but as a literal version which has to match exactly. In this case because it doesn't understand that the version being installed from the checkout is actually the same as the one specified in the `ch_util @ ...` line, it instead treats the `ch_util @ git+...` line as saying I want ch_util installed with exactly this spec from git, whereas before it would be sweet, ch_util is already installed, I guess I don't need to bother checking out the git repo.

**Comment by anjakefala** [comment]
Oh, that is so gross. Yeah, I don't think updating the requirements.txt to point to the same link will fix that.

I think we will want to file an issue.

**Comment by jrs65** [comment]
Ultimately, while mocking the `csd_to_unix` call might solve things here, we use the `<package> @ <git_repo>` format so widely, we're going to have breakages everywhere until we figure out a way to do this.

I mean even in the test context it's not obvious that installing the `ch_util` stub can *ever* satisfy a requirement specified as `ch_util @ git...`.

**Comment by anjakefala** [comment]
@jrs65 I agree with you! I misunderstood your earlier message. This is definitely a problem, and the way you described it, updating links as they suggest, will not fix it. I think we might need to file an issue. I will review their changelog for 21 to make sure stuff is not actually going to be fixed there, and file one.

**Comment by jrs65** [comment]
Yeah, this slightly simplified version illustrates the issue. If I clone `ch_util` and then do a `pip install .` it fails because:
```
ERROR: Cannot install ch-util and ch-util 20.10.0+12.gbe3c80f (from /Users/richard/tmp/pip_resolver_tests/ch_util) because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested ch-util 20.10.0+12.gbe3c80f (from /Users/richard/tmp/pip_resolver_tests/ch_util)
    chimedb-dataflag 0.1.1+23.g11bb640 depends on ch-util 20.10.0+12.gbe3c80f (from git+ssh://****@github.com/chime-experiment/ch_util.git)

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

*However*, if I simply do `pip install "ch_util@git+ssh://git@github.com/chime-experiment/ch_util.git"` without explicitly checking it out, it installs fine.

**Comment by jrs65** [comment]
I'm increasingly starting to think that the way to fix this is to use a custom PyPI index that points to the github repo versions. In those issues you linked @anjakefala this seems to be what the pip folks say is the way to solve this, and it's not as hard as I thought. This seems to give a guide how to do it (https://www.freecodecamp.org/news/how-to-use-github-as-a-pypi-server-1c3b0d07db2/).

Ultimately a package index is really just a structured set of html pages or files. Typically most of the tutorials tell you to just dump the tarballs in the right places, but it seems there's an alternative method where you can use links that tell pip how to install packages, but not provide the tarball itself. And they can use urls that only pip understands, e.g. `git+ssh://...` type ones. So we could have a public page which provides links to the private repos and if you point pip at this new package index all would be fine.

**Comment by anjakefala** [comment]
Oooo! Fun, yes. I can do this!

**Comment by ketiltrout** [comment]
That sounds great.

**Comment by jrs65** [comment]
See chime-experiment/Pipeline#92

**Pull request merged**
