### PR TITLE
fix(cdf): protect cdf from requiring ch_util

### PR DESCRIPTION
**Pull request by jrs65**

### CODE REVIEW

**Review by ketiltrout — APPROVED** [review]
Is there any benefit to putting this in a `try ... except ImportError`?

I can't figure out what you'd put in the exception handler.

This also strengthens my desire to pull `ephemeris` out of `ch_util` and make it its own thing.

**Comment by jrs65** [comment]
I can't understand why the tests now fail from the log 🤷

**Comment by ketiltrout** [comment]
> I can't understand why the tests now fail from the log 🤷

https://github.com/chime-experiment/chimedb_dataflag/blob/24906b6a6eeac81264fa0924006c2d15c6ef00bd/chimedb/dataflag/client.py#L314
is missing `()` at the end.

**Comment by ketiltrout** [comment]
At the time of the previous CI run (#11) `arrow` warned that this was deprecated:
> /opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/arrow/arrow.py:707: DeprecationWarning: For compatibility with the datetime.timestamp() method this property will be replaced with a method in the 1.0.0 release, please switch to the .int_timestamp property for identical behaviour as soon as possible.

Here: https://github.com/chime-experiment/chimedb_dataflag/runs/1773430280

**Comment by jrs65** [comment]
Good catch!

**Pull request merged**
